# 파이토치
### 이미지 처리에 특화
### CUDA 버전 너무 높으면 다른 의존성과 충돌 - 낮은 것이 안정적일 수 있음
### 훈련과 추론 data간에 차원을 맞춰야 함(학습 : 모델 4차원  -> 추론 : 4차원 입력)
##### https://pytorch.org/get-started/locally/
##### cmd : uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126(cuda 버전)
##### cmd : nvidia-smi(cuda 버전확인)

### 1. 기본 활용

In [5]:
import torch

torch.cuda.is_available()

False

In [3]:
torch.__version__

'2.8.0'

In [4]:
# tensor라는 type == array 
torch.tensor(5)

tensor(5)

In [5]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
data = [1,2,3,4,5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [6]:
import numpy as np

data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [9]:
torch.ones(3, 5) # 1로 채운 3 x 5개의 data 생성

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [10]:
torch.ones(512, 512) # 이미지 : 1(흰)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [11]:
torch.zeros(512, 512) # 이미지 : 0(검)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
torch.eye(5) # 단위행렬(대각선의 요소가 1 나머지는 0)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [15]:
torch.rand(5)

tensor([0.8881, 0.4669, 0.3050, 0.0500, 0.5202])

In [16]:
torch.rand(3, 3, 3)

tensor([[[0.9314, 0.3802, 0.4968],
         [0.3627, 0.5701, 0.8059],
         [0.3776, 0.3463, 0.1191]],

        [[0.6815, 0.3223, 0.3935],
         [0.5688, 0.9092, 0.0432],
         [0.9693, 0.5520, 0.3610]],

        [[0.0199, 0.8769, 0.5897],
         [0.9735, 0.1481, 0.3475],
         [0.5659, 0.2220, 0.8644]]])

In [17]:
# 훈련과 추론 data간에 차원을 맞춰야 함
data = torch.rand(3, 3, 3) # 3*3*3 = 27
data.dim()

3

In [18]:
data.view(9, 3) # 9*3 = 27
data.view(3, 9) # 3*9 = 27(행렬 전환 - 이미지 반전)

tensor([[0.2596, 0.7923, 0.1214, 0.3026, 0.6047, 0.4404, 0.5416, 0.6734, 0.6712],
        [0.5668, 0.9474, 0.2193, 0.5983, 0.7454, 0.1315, 0.5452, 0.2913, 0.1481],
        [0.2993, 0.2478, 0.1716, 0.4591, 0.5671, 0.5786, 0.1082, 0.4254, 0.1229]])

In [19]:
data.view(27) # 3차원을 1차원으로 변환

tensor([0.2596, 0.7923, 0.1214, 0.3026, 0.6047, 0.4404, 0.5416, 0.6734, 0.6712,
        0.5668, 0.9474, 0.2193, 0.5983, 0.7454, 0.1315, 0.5452, 0.2913, 0.1481,
        0.2993, 0.2478, 0.1716, 0.4591, 0.5671, 0.5786, 0.1082, 0.4254, 0.1229])

In [20]:
data.view(3, -1) # 3행으로 하고 열은 자동으로 설정

tensor([[0.2596, 0.7923, 0.1214, 0.3026, 0.6047, 0.4404, 0.5416, 0.6734, 0.6712],
        [0.5668, 0.9474, 0.2193, 0.5983, 0.7454, 0.1315, 0.5452, 0.2913, 0.1481],
        [0.2993, 0.2478, 0.1716, 0.4591, 0.5671, 0.5786, 0.1082, 0.4254, 0.1229]])

In [21]:
data.view(-1) # 1차원으로 변환(주로 사용)

tensor([0.2596, 0.7923, 0.1214, 0.3026, 0.6047, 0.4404, 0.5416, 0.6734, 0.6712,
        0.5668, 0.9474, 0.2193, 0.5983, 0.7454, 0.1315, 0.5452, 0.2913, 0.1481,
        0.2993, 0.2478, 0.1716, 0.4591, 0.5671, 0.5786, 0.1082, 0.4254, 0.1229])

In [22]:
data.shape # 모양

torch.Size([3, 3, 3])

In [23]:
data.dim() # 차원

3

In [24]:
data.dtype # 타입(중요)

torch.float32

### 2. 하드웨어 설정(중요)

In [25]:
torch.cuda.device_count()

0

In [ ]:
#torch.cuda.get_device_name(0)

AssertionError: Torch not compiled with CUDA enabled

In [27]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [28]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [29]:
data.to('cuda') # 1. gpu에 data 올리기(model/data 모두 같은 공간에서 처리해야 함 - 파라미터 적용)

AssertionError: Torch not compiled with CUDA enabled

In [30]:
data1 = torch.tensor([1,2,3]).cuda() # 2. gpu에 data 올리기
data1

AssertionError: Torch not compiled with CUDA enabled

In [31]:
data1.to('cpu') # gpu에서 cpu로 올리기

NameError: name 'data1' is not defined

In [ ]:
data.cuda() + data1 # 같은 공간에 옮겨서 처리

tensor([2, 4, 6], device='cuda:0')

In [ ]:
data = data.cuda()
data - data1

tensor([0, 0, 0], device='cuda:0')

### 3. 연산

In [34]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
data.min()

tensor(1)

In [36]:
data.min(dim=0) # 열(0)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [37]:
data.min(dim=1) # 행(1)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [ ]:
data.max(dim=0) # 열(0)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [ ]:
data.max(dim=1) # 행(1)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [38]:
data.dtype

torch.int64

In [39]:
data.type(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
data.dtype

torch.int64

### 4. 차원 편집

In [40]:
image = torch.rand(3, 128, 128) # 3차원 이미지
image = image.view(1, 3, 128, 128) # 4차원 이미지
image.shape

torch.Size([1, 3, 128, 128])

In [41]:
image = torch.rand(3, 128, 128) 
image = image.unsqueeze(dim=0) # 맨 앞 차원 추가
image.shape

torch.Size([1, 3, 128, 128])

In [42]:
data = torch.rand(1, 128, 128)
data.shape

torch.Size([1, 128, 128])

In [43]:
data = data.squeeze() # 맨 앞 차원 제거
data.shape

torch.Size([128, 128])

### 5. 모델 활용

In [3]:
import pandas as pd

df = pd.read_csv('../data/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [8]:
X_train = df.iloc[:, :13].values

# X_train = torch.tensor(X_train)
X_train = torch.FloatTensor(X_train)

y_train  = df.iloc[:, -1].values # 마지막 값만 
y_train = torch.FloatTensor(y_train)

In [9]:
import torch.nn as nn # 모델 생성에 필요한 함수 포함
from torch.optim.adam import Adam

# 모델 학습
# 13 => 100 => ReLU => 50 => ReLU => 1
model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(), # 활성화 함수(비선형)
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [10]:
for name, param in model.named_parameters():
    print(f"Name: {name}")
    print(f"Shape: {param.shape}")
    print(f"Values: {param}\n")

Name: 0.weight
Shape: torch.Size([100, 13])
Values: Parameter containing:
tensor([[ 0.1059,  0.1304, -0.2473,  ...,  0.1654, -0.2266, -0.0434],
        [-0.2063,  0.2501, -0.1128,  ..., -0.0722, -0.2576, -0.1383],
        [-0.0039, -0.0415,  0.0828,  ...,  0.0455, -0.0399,  0.0407],
        ...,
        [ 0.0774,  0.2099, -0.0816,  ...,  0.0180, -0.0346,  0.2214],
        [ 0.1526, -0.1995,  0.1974,  ...,  0.1155, -0.0940,  0.0748],
        [-0.2280, -0.0895,  0.1546,  ...,  0.1809,  0.0532, -0.1909]],
       requires_grad=True)

Name: 0.bias
Shape: torch.Size([100])
Values: Parameter containing:
tensor([ 0.0135,  0.2295, -0.1923, -0.0198, -0.2210, -0.1793, -0.2170,  0.1956,
        -0.1018, -0.1486, -0.0503,  0.2726, -0.1932,  0.0055,  0.1442,  0.2351,
         0.2767, -0.0635, -0.0181,  0.0771, -0.1591, -0.1050,  0.0953,  0.1774,
        -0.2754,  0.2690,  0.0167,  0.2450, -0.0018,  0.2761,  0.0673,  0.1560,
        -0.0265, -0.0135,  0.2013, -0.2146,  0.2205, -0.0260, -0.2480, -0.08

In [13]:
optim = Adam(model.parameters(), lr=0.001) # 최적화(탐색 크기 및 속도)함수 선택
criterion = nn.MSELoss() # 손실함수 선택
epochs = 200 

for epoch in range(epochs):
    
    optim.zero_grad() # 기울기 값을 0으로 초기화(누적 방지)
    
    y_pred = model(X_train) # 예측
    
    loss = criterion(y_pred, y_train.view(-1, 1)) # loss 값 계산
    
    loss.backward() # 역전파
    
    optim.step() # 가중치 업데이트(다음 진행)
    
    print('loss : ', loss.item()) # loss 값 확인(계속 감소하면 epoch 증가 고려)

loss :  1718.5030517578125
loss :  1178.234130859375
loss :  791.2654418945312
loss :  550.1005859375
loss :  424.1222229003906
loss :  367.2666320800781
loss :  349.30419921875
loss :  349.1273193359375
loss :  347.3112487792969
loss :  334.42059326171875
loss :  310.58795166015625
loss :  276.5933837890625
loss :  237.5851593017578
loss :  197.58737182617188
loss :  161.08303833007812
loss :  131.68991088867188
loss :  110.4965591430664
loss :  98.28783416748047
loss :  93.9709243774414
loss :  95.0888442993164
loss :  98.50685119628906
loss :  101.7686538696289
loss :  103.12773132324219
loss :  102.00838470458984
loss :  98.59288787841797
loss :  93.68972778320312
loss :  88.39707946777344
loss :  83.77790069580078
loss :  80.61080169677734
loss :  79.21497344970703
loss :  79.44326782226562
loss :  80.75498962402344
loss :  82.41484832763672
loss :  83.7080307006836
loss :  84.09577178955078
loss :  83.37556457519531
loss :  81.65596771240234
loss :  79.2805404663086
loss :  76.69

In [14]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.1155,  0.1100, -0.2732,  ...,  0.1456, -0.2396, -0.0290],
                      [-0.2221,  0.2501, -0.1248,  ..., -0.0838, -0.2634, -0.1532],
                      [-0.0039, -0.0415,  0.0828,  ...,  0.0455, -0.0399,  0.0407],
                      ...,
                      [ 0.0774,  0.2099, -0.0816,  ...,  0.0180, -0.0346,  0.2214],
                      [ 0.1348, -0.1934,  0.1760,  ...,  0.1026, -0.1052,  0.0673],
                      [-0.2280, -0.0895,  0.1546,  ...,  0.1809,  0.0532, -0.1909]])),
             ('0.bias',
              tensor([-0.0105,  0.2183, -0.1923,  0.0083, -0.2165, -0.1783, -0.2281,  0.1782,
                      -0.1018, -0.1671, -0.0257,  0.2546, -0.1882,  0.0309,  0.1305,  0.2351,
                       0.2950, -0.0819, -0.0181,  0.0771, -0.1495, -0.1050,  0.0802,  0.1774,
                      -0.2936,  0.2793,  0.0167,  0.2301, -0.0018,  0.2747,  0.0782,  0.1722,
                      -0.0555, -0.0162, 

In [15]:
# GPU 사용 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

optim = Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
epochs = 200
batch_size = 100

for epoch in range(epochs):
    for temp in range(len(X_train) // batch_size):
        
        s = temp * batch_size # 0 * 100
        e = s + batch_size    # 100
        
        X = X_train[s:e]
        y = y_train[s:e]
    
        optim.zero_grad()
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optim.step()

        print('loss : ', loss.item())

/Users/minwoojeon/J/Code/deep-learning/.venv/lib/python3.11/site-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss :  55.77470779418945
loss :  181.104736328125
loss :  138.63299560546875
loss :  110.1680908203125
loss :  104.98490142822266
loss :  67.50037384033203
loss :  110.71512603759766
loss :  110.31269836425781
loss :  102.3504409790039
loss :  36.832801818847656
loss :  46.06622314453125
loss :  125.60594940185547
loss :  128.44873046875
loss :  101.14525604248047
loss :  40.6799430847168
loss :  48.708580017089844
loss :  109.6517105102539
loss :  104.44902801513672
loss :  105.7396011352539
loss :  59.61597442626953
loss :  49.12688064575195
loss :  109.31787872314453
loss :  116.74935913085938
loss :  97.41619110107422
loss :  39.127967834472656
loss :  42.855873107910156
loss :  113.64601135253906
loss :  121.91422271728516
loss :  96.5797348022461
loss :  45.05255889892578
loss :  44.812992095947266
loss :  107.10563659667969
loss :  110.18820190429688
loss :  98.68466186523438
loss :  50.553550720214844
loss :  45.0528450012207
loss :  107.99862670898438
loss :  115.864799499511