# 파이토치
### 이미지 처리에 특화
### CUDA 버전 너무 높으면 다른 의존성과 충돌 - 낮은 것이 안정적일 수 있음
### 훈련과 추론 data간에 차원을 맞춰야 함(학습 : 모델 4차원  -> 추론 : 4차원 입력)
##### https://pytorch.org/get-started/locally/
##### cmd : uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126(cuda 버전)
##### cmd : nvidia-smi(cuda 버전확인)

### 1. 기본 활용

In [135]:
import torch

torch.cuda.is_available()

True

In [136]:
torch.__version__

'2.8.0+cu126'

In [137]:
# tensor라는 type == array 
torch.tensor(5)

tensor(5)

In [138]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [139]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [140]:
data = [1,2,3,4,5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [141]:
import numpy as np

data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [142]:
torch.ones(3, 5) # 1로 채운 3 x 5개의 data 생성

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [143]:
torch.ones(512, 512) # 이미지 : 1(흰)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [144]:
torch.zeros(512, 512) # 이미지 : 0(검)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [145]:
torch.eye(5) # 단위행렬(대각선의 요소가 1 나머지는 0)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [146]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [148]:
torch.rand(5)

tensor([0.9306, 0.1654, 0.5932, 0.1055, 0.9525])

In [149]:
torch.rand(3, 3, 3)

tensor([[[0.7855, 0.9344, 0.9691],
         [0.2090, 0.8834, 0.6439],
         [0.7475, 0.8471, 0.1604]],

        [[0.6072, 0.7863, 0.0119],
         [0.3712, 0.0155, 0.5355],
         [0.6226, 0.4872, 0.8430]],

        [[0.3238, 0.6757, 0.4946],
         [0.5372, 0.3537, 0.1209],
         [0.0098, 0.1240, 0.1122]]])

In [150]:
# 훈련과 추론 data간에 차원을 맞춰야 함
data = torch.rand(3, 3, 3) # 3*3*3 = 27
data.dim()

3

In [151]:
data.view(9, 3) # 9*3 = 27
data.view(3, 9) # 3*9 = 27(행렬 전환 - 이미지 반전)

tensor([[0.0150, 0.4982, 0.6671, 0.2635, 0.5322, 0.3222, 0.1606, 0.2517, 0.9910],
        [0.8049, 0.4751, 0.6013, 0.7166, 0.1626, 0.4786, 0.7037, 0.0994, 0.1265],
        [0.1036, 0.1701, 0.0511, 0.3545, 0.4341, 0.9867, 0.0782, 0.9377, 0.4752]])

In [152]:
data.view(27) # 3차원을 1차원으로 변환

tensor([0.0150, 0.4982, 0.6671, 0.2635, 0.5322, 0.3222, 0.1606, 0.2517, 0.9910,
        0.8049, 0.4751, 0.6013, 0.7166, 0.1626, 0.4786, 0.7037, 0.0994, 0.1265,
        0.1036, 0.1701, 0.0511, 0.3545, 0.4341, 0.9867, 0.0782, 0.9377, 0.4752])

In [153]:
data.view(3, -1) # 3행으로 하고 열은 자동으로 설정

tensor([[0.0150, 0.4982, 0.6671, 0.2635, 0.5322, 0.3222, 0.1606, 0.2517, 0.9910],
        [0.8049, 0.4751, 0.6013, 0.7166, 0.1626, 0.4786, 0.7037, 0.0994, 0.1265],
        [0.1036, 0.1701, 0.0511, 0.3545, 0.4341, 0.9867, 0.0782, 0.9377, 0.4752]])

In [154]:
data.view(-1) # 1차원으로 변환(주로 사용)

tensor([0.0150, 0.4982, 0.6671, 0.2635, 0.5322, 0.3222, 0.1606, 0.2517, 0.9910,
        0.8049, 0.4751, 0.6013, 0.7166, 0.1626, 0.4786, 0.7037, 0.0994, 0.1265,
        0.1036, 0.1701, 0.0511, 0.3545, 0.4341, 0.9867, 0.0782, 0.9377, 0.4752])

In [155]:
data.shape # 모양

torch.Size([3, 3, 3])

In [156]:
data.dim() # 차원

3

In [157]:
data.dtype # 타입(중요)

torch.float32

### 2. 하드웨어 설정(중요)

In [158]:
torch.cuda.device_count()

1

In [159]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [160]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [161]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [162]:
data.to('cuda') # 1. gpu에 data 올리기(model/data 모두 같은 공간에서 처리해야 함 - 파라미터 적용)

tensor([1, 2, 3], device='cuda:0')

In [163]:
data1 = torch.tensor([1,2,3]).cuda() # 2. gpu에 data 올리기
data1

tensor([1, 2, 3], device='cuda:0')

In [164]:
data1.to('cpu') # gpu에서 cpu로 올리기

tensor([1, 2, 3])

In [165]:
data.cuda() + data1 # 같은 공간에 옮겨서 처리

tensor([2, 4, 6], device='cuda:0')

In [166]:
data = data.cuda()
data - data1

tensor([0, 0, 0], device='cuda:0')

### 3. 연산

In [167]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [168]:
data.min()

tensor(1)

In [169]:
data.min(dim=0) # 열(0)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [170]:
data.min(dim=1) # 행(1)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [171]:
data.max(dim=0) # 열(0)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [172]:
data.max(dim=1) # 행(1)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [173]:
data.dtype

torch.int64

In [174]:
data.type(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [175]:
data.dtype

torch.int64

### 4. 차원 편집

In [176]:
image = torch.rand(3, 128, 128) # 3차원 이미지
image = image.view(1, 3, 128, 128) # 4차원 이미지
image.shape

torch.Size([1, 3, 128, 128])

In [177]:
image = torch.rand(3, 128, 128) 
image = image.unsqueeze(dim=0) # 맨 앞 차원 추가
image.shape

torch.Size([1, 3, 128, 128])

In [178]:
data = torch.rand(1, 128, 128)
data.shape

torch.Size([1, 128, 128])

In [179]:
data = data.squeeze() # 맨 앞 차원 제거
data.shape

torch.Size([128, 128])

### 5. 모델 활용

In [180]:
import pandas as pd

df = pd.read_csv('data/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [181]:
X_train = df.iloc[:, :13].values

# X_train = torch.tensor(X_train)
X_train = torch.FloatTensor(X_train)

y_train  = df.iloc[:, -1].values # 마지막 값만 
y_train = torch.FloatTensor(y_train)

In [182]:
import torch.nn as nn # 모델 생성에 필요한 함수 포함
from torch.optim.adam import Adam

# 모델 학습
# 13 => 100 => ReLU => 50 => ReLU => 1
model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(), # 활성화 함수(비선형)
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [183]:
for name, param in model.named_parameters():
    print(f"Name: {name}")
    print(f"Shape: {param.shape}")
    print(f"Values: {param}\n")

Name: 0.weight
Shape: torch.Size([100, 13])
Values: Parameter containing:
tensor([[ 0.2678, -0.0858, -0.1227,  ...,  0.1063,  0.1780,  0.0986],
        [-0.0619,  0.2396, -0.2533,  ..., -0.2146, -0.1039,  0.0191],
        [ 0.1487,  0.0104, -0.1483,  ..., -0.1522, -0.1509, -0.1409],
        ...,
        [ 0.0588,  0.0869, -0.0101,  ...,  0.2699,  0.0602,  0.2079],
        [-0.1405,  0.2344,  0.0495,  ..., -0.0822,  0.0715,  0.0225],
        [ 0.1876,  0.1566,  0.1838,  ..., -0.0011,  0.1771,  0.1670]],
       requires_grad=True)

Name: 0.bias
Shape: torch.Size([100])
Values: Parameter containing:
tensor([ 0.0994,  0.1843, -0.0412, -0.2049,  0.0775,  0.2287, -0.0667,  0.1358,
         0.1152,  0.1284, -0.1881, -0.2112, -0.0962, -0.1001,  0.1493, -0.2513,
        -0.0921,  0.1427, -0.0603, -0.1886,  0.1239, -0.0554, -0.0473, -0.0945,
         0.2428, -0.2761,  0.1597, -0.1493, -0.0070,  0.2302, -0.1298,  0.2208,
        -0.2568, -0.1261, -0.1597,  0.0049, -0.0128,  0.0041,  0.0433,  0.01

In [184]:
optim = Adam(model.parameters(), lr=0.001) # 최적화(탐색 크기 및 속도)함수 선택
criterion = nn.MSELoss() # 손실함수 선택
epochs = 200 

for epoch in range(epochs):
    
    optim.zero_grad() # 기울기 값을 0으로 초기화(누적 방지)
    
    y_pred = model(X_train) # 예측
    
    loss = criterion(y_pred, y_train.view(-1, 1)) # loss 값 계산
    
    loss.backward() # 역전파
    
    optim.step() # 가중치 업데이트(다음 진행)
    
    print('loss : ', loss.item()) # loss 값 확인(계속 감소하면 epoch 증가 고려)

loss :  241.25270080566406
loss :  142.2334747314453
loss :  151.1941375732422
loss :  134.6925811767578
loss :  95.9632568359375
loss :  73.39851379394531
loss :  77.30633544921875
loss :  87.97480010986328
loss :  87.84689331054688
loss :  79.9390640258789
loss :  76.0277328491211
loss :  79.80854034423828
loss :  82.26969909667969
loss :  77.45519256591797
loss :  69.63533020019531
loss :  65.0558853149414
loss :  65.23880004882812
loss :  66.91819763183594
loss :  66.79747772216797
loss :  64.93596649169922
loss :  63.78530502319336
loss :  64.81431579589844
loss :  66.80905151367188
loss :  67.47039031982422
loss :  66.1012954711914
loss :  64.09013366699219
loss :  63.05476379394531
loss :  63.12393569946289
loss :  63.17192840576172
loss :  62.42697525024414
loss :  61.37428665161133
loss :  60.996517181396484
loss :  61.45295333862305
loss :  61.9716796875
loss :  61.750701904296875
loss :  60.96827697753906
loss :  60.414634704589844
loss :  60.352481842041016
loss :  60.31045

In [185]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.4416, -0.0816, -0.1731,  ...,  0.0794,  0.1873, -0.0137],
                      [-0.0798,  0.2187, -0.2885,  ..., -0.3209, -0.0670, -0.1988],
                      [ 0.0644, -0.0416, -0.1089,  ..., -0.1904, -0.1277, -0.3355],
                      ...,
                      [ 0.0600,  0.1458, -0.1198,  ...,  0.2422,  0.0652,  0.1159],
                      [-0.0821,  0.1568, -0.0477,  ..., -0.1333,  0.0545, -0.0744],
                      [ 0.1647,  0.1416,  0.1406,  ..., -0.0404,  0.1652,  0.0832]])),
             ('0.bias',
              tensor([ 0.1125,  0.2596,  0.0401, -0.2172,  0.0533,  0.2072, -0.0579,  0.1478,
                       0.1264,  0.1317, -0.1786, -0.2137, -0.0962, -0.1369,  0.1400, -0.2279,
                      -0.0921,  0.1271, -0.0616, -0.1326,  0.1060, -0.0436, -0.0322, -0.1039,
                       0.2525, -0.2761,  0.2012, -0.1327, -0.0117,  0.2302, -0.1298,  0.2208,
                      -0.2568, -0.1314, 

In [186]:
# GPU 사용 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

optim = Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
epochs = 200
batch_size = 100

for epoch in range(epochs):
    for temp in range(len(X_train) // batch_size):
        
        s = temp * batch_size # 0 * 100
        e = s + batch_size    # 100
        
        X = X_train[s:e]
        y = y_train[s:e]
    
        optim.zero_grad()
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optim.step()

        print('loss : ', loss.item())

loss :  63.90715408325195
loss :  260.35955810546875
loss :  154.4896697998047
loss :  210.74359130859375
loss :  239.41749572753906
loss :  68.94908905029297
loss :  129.64222717285156
loss :  162.2895965576172
loss :  150.14764404296875
loss :  73.15821075439453
loss :  59.696197509765625
loss :  134.8520965576172
loss :  118.31626892089844
loss :  121.11754608154297
loss :  74.82767486572266
loss :  73.53008270263672
loss :  123.50568389892578
loss :  103.26597595214844
loss :  113.54100036621094
loss :  51.41214370727539
loss :  46.996490478515625
loss :  120.8689956665039
loss :  151.30172729492188
loss :  104.08299255371094
loss :  39.97507858276367
loss :  44.93535614013672
loss :  110.28019714355469
loss :  116.70259857177734
loss :  106.20465087890625
loss :  73.62776184082031


c:\walker\code\deep-learning\.venv\Lib\site-packages\torch\nn\modules\loss.py:616: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss :  49.18620681762695
loss :  108.07474517822266
loss :  116.54122161865234
loss :  100.59918212890625
loss :  41.27511978149414
loss :  43.55937576293945
loss :  111.96174621582031
loss :  127.24317169189453
loss :  102.52485656738281
loss :  40.2081184387207
loss :  46.29469299316406
loss :  107.91692352294922
loss :  107.00477600097656
loss :  104.90272521972656
loss :  47.30099105834961
loss :  47.74473571777344
loss :  107.31649780273438
loss :  115.40717315673828
loss :  102.9870376586914
loss :  37.02814483642578
loss :  43.75472640991211
loss :  107.01167297363281
loss :  114.9861068725586
loss :  101.31128692626953
loss :  43.9122428894043
loss :  46.25493621826172
loss :  104.89346313476562
loss :  111.79027557373047
loss :  100.64571380615234
loss :  41.401493072509766
loss :  44.14778518676758
loss :  105.17837524414062
loss :  117.34410858154297
loss :  100.53702545166016
loss :  39.50503921508789
loss :  44.641319274902344
loss :  104.1772689819336
loss :  111.8110733