# 파이토치
### 이미지 처리에 특화
### CUDA 버전 너무 높으면 다른 의존성과 충돌 - 낮은 것이 안정적일 수 있음
### 훈련과 추론 data간에 차원을 맞춰야 함(학습 : 모델 4차원  -> 추론 : 4차원 입력)
##### https://pytorch.org/get-started/locally/
##### cmd : uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126(cuda 버전)
##### cmd : nvidia-smi(cuda 버전확인)

### 1. 기본 활용

In [2]:
import torch

torch.cuda.is_available()

True

In [3]:
torch.__version__

'2.8.0+cu126'

In [4]:
# tensor라는 type == array 
torch.tensor(5)

tensor(5)

In [5]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [6]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
data = [1,2,3,4,5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [8]:
import numpy as np

data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [9]:
torch.ones(3, 5) # 1로 채운 3 x 5개의 data 생성

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [10]:
torch.ones(512, 512) # 이미지 : 1(흰)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [11]:
torch.zeros(512, 512) # 이미지 : 0(검)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
torch.eye(5) # 단위행렬(대각선의 요소가 1 나머지는 0)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [15]:
torch.rand(5)

tensor([0.8031, 0.3610, 0.5579, 0.2391, 0.9281])

In [16]:
torch.rand(3, 3, 3)

tensor([[[0.5000, 0.7573, 0.8516],
         [0.2283, 0.5278, 0.3146],
         [0.3244, 0.2240, 0.2109]],

        [[0.1333, 0.5523, 0.5743],
         [0.4822, 0.6583, 0.1073],
         [0.3081, 0.3659, 0.6293]],

        [[0.4425, 0.5879, 0.5490],
         [0.9255, 0.4956, 0.7592],
         [0.7293, 0.4287, 0.3339]]])

In [17]:
# 훈련과 추론 data간에 차원을 맞춰야 함
data = torch.rand(3, 3, 3) # 3*3*3 = 27
data.dim()

3

In [18]:
data.view(9, 3) # 9*3 = 27
data.view(3, 9) # 3*9 = 27(행렬 전환 - 이미지 반전)

tensor([[0.1730, 0.1030, 0.0515, 0.6148, 0.2885, 0.4123, 0.7614, 0.9527, 0.7365],
        [0.6878, 0.9188, 0.3300, 0.0539, 0.3904, 0.6056, 0.1930, 0.1274, 0.4462],
        [0.0891, 0.5417, 0.7978, 0.9331, 0.6954, 0.4693, 0.5764, 0.6349, 0.5695]])

In [19]:
data.view(27) # 3차원을 1차원으로 변환

tensor([0.1730, 0.1030, 0.0515, 0.6148, 0.2885, 0.4123, 0.7614, 0.9527, 0.7365,
        0.6878, 0.9188, 0.3300, 0.0539, 0.3904, 0.6056, 0.1930, 0.1274, 0.4462,
        0.0891, 0.5417, 0.7978, 0.9331, 0.6954, 0.4693, 0.5764, 0.6349, 0.5695])

In [20]:
data.view(3, -1) # 3행으로 하고 열은 자동으로 설정

tensor([[0.1730, 0.1030, 0.0515, 0.6148, 0.2885, 0.4123, 0.7614, 0.9527, 0.7365],
        [0.6878, 0.9188, 0.3300, 0.0539, 0.3904, 0.6056, 0.1930, 0.1274, 0.4462],
        [0.0891, 0.5417, 0.7978, 0.9331, 0.6954, 0.4693, 0.5764, 0.6349, 0.5695]])

In [21]:
data.view(-1) # 1차원으로 변환(주로 사용)

tensor([0.1730, 0.1030, 0.0515, 0.6148, 0.2885, 0.4123, 0.7614, 0.9527, 0.7365,
        0.6878, 0.9188, 0.3300, 0.0539, 0.3904, 0.6056, 0.1930, 0.1274, 0.4462,
        0.0891, 0.5417, 0.7978, 0.9331, 0.6954, 0.4693, 0.5764, 0.6349, 0.5695])

In [22]:
data.shape # 모양

torch.Size([3, 3, 3])

In [23]:
data.dim() # 차원

3

In [24]:
data.dtype # 타입(중요)

torch.float32

### 2. 하드웨어 설정(중요)

In [25]:
torch.cuda.device_count()

1

In [26]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [27]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [28]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [29]:
data.to('cuda') # 1. gpu에 data 올리기(model/data 모두 같은 공간에서 처리해야 함 - 파라미터 적용)

tensor([1, 2, 3], device='cuda:0')

In [30]:
data1 = torch.tensor([1,2,3]).cuda() # 2. gpu에 data 올리기
data1

tensor([1, 2, 3], device='cuda:0')

In [31]:
data1.to('cpu') # gpu에서 cpu로 올리기

tensor([1, 2, 3])

In [32]:
data.cuda() + data1 # 같은 공간에 옮겨서 처리

tensor([2, 4, 6], device='cuda:0')

In [33]:
data = data.cuda()
data - data1

tensor([0, 0, 0], device='cuda:0')

### 3. 연산

In [34]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
data.min()

tensor(1)

In [36]:
data.min(dim=0) # 열(0)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [37]:
data.min(dim=1) # 행(1)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [38]:
data.max(dim=0) # 열(0)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [39]:
data.max(dim=1) # 행(1)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [40]:
data.dtype

torch.int64

In [41]:
data.type(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [42]:
data.dtype

torch.int64

### 4. 차원 편집

In [43]:
image = torch.rand(3, 128, 128) # 3차원 이미지
image = image.view(1, 3, 128, 128) # 4차원 이미지
image.shape

torch.Size([1, 3, 128, 128])

In [44]:
image = torch.rand(3, 128, 128) 
image = image.unsqueeze(dim=0) # 맨 앞 차원 추가
image.shape

torch.Size([1, 3, 128, 128])

In [45]:
data = torch.rand(1, 128, 128)
data.shape

torch.Size([1, 128, 128])

In [46]:
data = data.squeeze() # 맨 앞 차원 제거
data.shape

torch.Size([128, 128])

### 5. 모델 활용

In [47]:
import pandas as pd

df = pd.read_csv('data/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [48]:
X_train = df.iloc[:, :13].values

# X_train = torch.tensor(X_train)
X_train = torch.FloatTensor(X_train)

y_train  = df.iloc[:, -1].values # 마지막 값만 
y_train = torch.FloatTensor(y_train)

In [49]:
import torch.nn as nn # 모델 생성에 필요한 함수 포함
from torch.optim.adam import Adam

# 모델 학습
# 13 => 100 => ReLU => 50 => ReLU => 1
model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(), # 활성화 함수(비선형)
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [50]:
for name, param in model.named_parameters():
    print(f"Name: {name}")
    print(f"Shape: {param.shape}")
    print(f"Values: {param}\n")

Name: 0.weight
Shape: torch.Size([100, 13])
Values: Parameter containing:
tensor([[-0.2091,  0.1801, -0.1821,  ..., -0.2544, -0.1559, -0.1905],
        [-0.2006,  0.0940, -0.2521,  ...,  0.1317,  0.2371,  0.2363],
        [ 0.0527,  0.0964, -0.0203,  ..., -0.1674, -0.0820, -0.0912],
        ...,
        [-0.2192, -0.1853,  0.2737,  ..., -0.0340,  0.0370,  0.1508],
        [ 0.1964, -0.1164, -0.0647,  ...,  0.2700,  0.0734, -0.0888],
        [ 0.0474, -0.1828, -0.0224,  ...,  0.0627,  0.1649, -0.2285]],
       requires_grad=True)

Name: 0.bias
Shape: torch.Size([100])
Values: Parameter containing:
tensor([ 0.1459,  0.0088,  0.1868, -0.0209,  0.2619,  0.2074,  0.1258,  0.1643,
         0.1035,  0.0897,  0.0253, -0.1171,  0.0468,  0.2413, -0.1991,  0.0389,
         0.1814,  0.1577, -0.2210, -0.1917,  0.0264,  0.0977, -0.1961, -0.2058,
        -0.0060, -0.1403,  0.0568,  0.1599,  0.0784,  0.1910,  0.0623, -0.0247,
         0.2218, -0.0663, -0.2038,  0.1276,  0.0043,  0.1705, -0.2034, -0.10

In [51]:
optim = Adam(model.parameters(), lr=0.001) # 최적화(탐색 크기 및 속도)함수 선택
criterion = nn.MSELoss() # 손실함수 선택
epochs = 200 

for epoch in range(epochs):
    
    optim.zero_grad() # 기울기 값을 0으로 초기화(누적 방지)
    
    y_pred = model(X_train) # 예측
    
    loss = criterion(y_pred, y_train.view(-1, 1)) # loss 값 계산
    
    loss.backward() # 역전파
    
    optim.step() # 가중치 업데이트(다음 진행)
    
    print('loss : ', loss.item()) # loss 값 확인(계속 감소하면 epoch 증가 고려)

loss :  250.86962890625
loss :  116.08440399169922
loss :  80.24451446533203
loss :  110.32664489746094
loss :  133.69998168945312
loss :  124.2442626953125
loss :  98.20609283447266
loss :  75.53921508789062
loss :  66.73704528808594
loss :  71.09789276123047
loss :  80.3309326171875
loss :  85.80316925048828
loss :  83.96558380126953
loss :  76.66825103759766
loss :  68.40853881835938
loss :  64.1466064453125
loss :  65.68810272216797
loss :  70.04893493652344
loss :  72.59082794189453
loss :  71.11671447753906
loss :  66.86531066894531
loss :  62.659141540527344
loss :  60.77091598510742
loss :  61.55466842651367
loss :  63.6263313293457
loss :  65.06535339355469
loss :  64.84686279296875
loss :  63.25650405883789
loss :  61.46051788330078
loss :  60.584739685058594
loss :  60.92218017578125
loss :  61.793643951416016
loss :  62.172183990478516
loss :  61.57530975341797
loss :  60.341033935546875
loss :  59.26536178588867
loss :  58.876651763916016
loss :  59.15911865234375
loss :  

In [52]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.2091,  0.1801, -0.1821,  ..., -0.2544, -0.1559, -0.1905],
                      [-0.2266,  0.0956, -0.2746,  ...,  0.1059,  0.2424,  0.1277],
                      [ 0.1099,  0.1317, -0.0303,  ..., -0.1641, -0.0782, -0.0130],
                      ...,
                      [-0.1370, -0.1563,  0.3107,  ...,  0.0082,  0.0289,  0.3151],
                      [ 0.2634, -0.1181, -0.0482,  ...,  0.2859,  0.0736,  0.0065],
                      [ 0.1465, -0.0815, -0.0935,  ...,  0.0403,  0.1714, -0.2920]])),
             ('0.bias',
              tensor([ 0.1459,  0.0194,  0.1746,  0.0320,  0.2688,  0.2074,  0.1258,  0.1518,
                       0.1035,  0.0831,  0.0253, -0.1171,  0.0565,  0.2413, -0.1205,  0.0535,
                       0.1650,  0.1784, -0.2208, -0.1836,  0.0513,  0.0977, -0.0165, -0.1976,
                       0.0070, -0.1403,  0.0672,  0.1599,  0.0784,  0.1985,  0.0623, -0.0287,
                       0.2381, -0.0663, 

In [53]:
# GPU 사용 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

optim = Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
epochs = 200
batch_size = 100

for epoch in range(epochs):
    for temp in range(len(X_train) // batch_size):
        
        s = temp * batch_size # 0 * 100
        e = s + batch_size    # 100
        
        X = X_train[s:e]
        y = y_train[s:e]
    
        optim.zero_grad()
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optim.step()

        print('loss : ', loss.item())

c:\walker\code\deep-learning\.venv\Lib\site-packages\torch\nn\modules\loss.py:616: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


loss :  64.26487731933594
loss :  172.74830627441406
loss :  148.2445068359375
loss :  162.296142578125
loss :  175.07603454589844
loss :  54.00504684448242
loss :  119.8480453491211
loss :  156.4344024658203
loss :  117.05152130126953
loss :  52.5182991027832
loss :  50.335609436035156
loss :  122.49315643310547
loss :  122.99473571777344
loss :  108.62812042236328
loss :  59.907474517822266
loss :  59.29724884033203
loss :  116.50807189941406
loss :  101.72052001953125
loss :  112.54727172851562
loss :  58.339962005615234
loss :  46.801998138427734
loss :  110.93460083007812
loss :  128.19705200195312
loss :  102.21803283691406
loss :  44.220767974853516
loss :  42.42521286010742
loss :  110.5284194946289
loss :  125.22572326660156
loss :  99.1503677368164
loss :  54.29301071166992
loss :  44.86939239501953
loss :  107.14364624023438
loss :  112.08338165283203
loss :  101.037841796875
loss :  52.762359619140625
loss :  43.9246940612793
loss :  107.7282485961914
loss :  121.2330322265