# 파이토치
### 이미지 처리에 특화
### CUDA 버전 너무 높으면 다른 의존성과 충돌 - 낮은 것이 안정적일 수 있음
### 훈련과 추론 data간에 차원을 맞춰야 함(학습 : 모델 4차원  -> 추론 : 4차원 입력)
##### https://pytorch.org/get-started/locally/
##### cmd : uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126(cuda 버전)
##### cmd : nvidia-smi(cuda 버전확인)

### 1. 기본 활용

In [86]:
import torch

torch.cuda.is_available()

True

In [87]:
torch.__version__

'2.8.0+cu126'

In [88]:
# tensor라는 type == array 
torch.tensor(5)

tensor(5)

In [89]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [90]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [91]:
data = [1,2,3,4,5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [92]:
import numpy as np

data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [93]:
torch.ones(3, 5) # 1로 채운 3 x 5개의 data 생성

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [94]:
torch.ones(512, 512) # 이미지 : 1(흰)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [95]:
torch.zeros(512, 512) # 이미지 : 0(검)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [96]:
torch.eye(5) # 단위행렬(대각선의 요소가 1 나머지는 0)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [97]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [99]:
torch.rand(5)

tensor([0.3705, 0.9748, 0.9446, 0.5988, 0.1571])

In [100]:
torch.rand(3, 3, 3)

tensor([[[0.6161, 0.5458, 0.3332],
         [0.2866, 0.1125, 0.1595],
         [0.4735, 0.1178, 0.5041]],

        [[0.0918, 0.1126, 0.3282],
         [0.4008, 0.9338, 0.5264],
         [0.4327, 0.8287, 0.0964]],

        [[0.3693, 0.9160, 0.8084],
         [0.3003, 0.8294, 0.2425],
         [0.4915, 0.1954, 0.9136]]])

In [101]:
# 훈련과 추론 data간에 차원을 맞춰야 함
data = torch.rand(3, 3, 3) # 3*3*3 = 27
data.dim()

3

In [ ]:
data.view(9, 3) # 9*3 = 27
data.view(3, 9) # 3*9 = 27(행렬 전환 - 이미지 반전)

tensor([[0.8438, 0.1055, 0.7333, 0.8939, 0.3684, 0.4597, 0.8943, 0.3518, 0.6823],
        [0.9227, 0.0083, 0.8861, 0.2400, 0.8006, 0.9530, 0.9965, 0.0996, 0.9467],
        [0.2374, 0.6591, 0.1932, 0.5844, 0.4461, 0.2534, 0.3255, 0.1613, 0.8221]])

In [103]:
data.view(27) # 3차원을 1차원으로 변환

tensor([0.8438, 0.1055, 0.7333, 0.8939, 0.3684, 0.4597, 0.8943, 0.3518, 0.6823,
        0.9227, 0.0083, 0.8861, 0.2400, 0.8006, 0.9530, 0.9965, 0.0996, 0.9467,
        0.2374, 0.6591, 0.1932, 0.5844, 0.4461, 0.2534, 0.3255, 0.1613, 0.8221])

In [104]:
data.view(3, -1) # 3행으로 하고 열은 자동으로 설정

tensor([[0.8438, 0.1055, 0.7333, 0.8939, 0.3684, 0.4597, 0.8943, 0.3518, 0.6823],
        [0.9227, 0.0083, 0.8861, 0.2400, 0.8006, 0.9530, 0.9965, 0.0996, 0.9467],
        [0.2374, 0.6591, 0.1932, 0.5844, 0.4461, 0.2534, 0.3255, 0.1613, 0.8221]])

In [105]:
data.view(-1) # 1차원으로 변환(주로 사용)

tensor([0.8438, 0.1055, 0.7333, 0.8939, 0.3684, 0.4597, 0.8943, 0.3518, 0.6823,
        0.9227, 0.0083, 0.8861, 0.2400, 0.8006, 0.9530, 0.9965, 0.0996, 0.9467,
        0.2374, 0.6591, 0.1932, 0.5844, 0.4461, 0.2534, 0.3255, 0.1613, 0.8221])

In [106]:
data.shape # 모양

torch.Size([3, 3, 3])

In [107]:
data.dim() # 차원

3

In [108]:
data.dtype # 타입(중요)

torch.float32

### 2. 하드웨어 설정(중요)

In [109]:
torch.cuda.device_count()

1

In [110]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [111]:
device = torch.device('cuda:1')
device

device(type='cuda', index=1)

In [112]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [113]:
data.to('cuda') # 1. gpu에 data 올리기(model/data 모두 같은 공간에서 처리해야 함 - 파라미터 적용)

tensor([1, 2, 3], device='cuda:0')

In [114]:
data1 = torch.tensor([1,2,3]).cuda() # 2. gpu에 data 올리기
data1

tensor([1, 2, 3], device='cuda:0')

In [115]:
data1.to('cpu') # gpu에서 cpu로 올리기

tensor([1, 2, 3])

In [116]:
data.cuda() + data1 # 같은 공간에 옮겨서 처리

tensor([2, 4, 6], device='cuda:0')

In [117]:
data = data.cuda()
data - data1

tensor([0, 0, 0], device='cuda:0')

### 3. 연산

In [118]:
data = torch.tensor([[1,2,3],[4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [119]:
data.min()

tensor(1)

In [120]:
data.min(dim=0) # 열(0)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [121]:
data.min(dim=1) # 행(1)기준으로 작은 숫자 / index

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [122]:
data.max(dim=0) # 열(0)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))

In [123]:
data.max(dim=1) # 행(1)기준으로 큰 숫자 / index

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [124]:
data.dtype

torch.int64

In [125]:
data.type(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [126]:
data.dtype

torch.int64

### 4. 차원 편집

In [127]:
image = torch.rand(3, 128, 128) # 3차원 이미지
image = image.view(1, 3, 128, 128) # 4차원 이미지
image.shape

torch.Size([1, 3, 128, 128])

In [128]:
image = torch.rand(3, 128, 128) 
image = image.unsqueeze(dim=0) # 맨 앞 차원 추가
image.shape

torch.Size([1, 3, 128, 128])

In [129]:
data = torch.rand(1, 128, 128)
data.shape

torch.Size([1, 128, 128])

In [130]:
data = data.squeeze() # 맨 앞 차원 제거
data.shape

torch.Size([128, 128])

### 5. 모델 활용

In [131]:
import pandas as pd

df = pd.read_csv('data/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [ ]:
X_train = df.iloc[:, :13].values

# X_train = torch.tensor(X_train)
X_train = torch.FloatTensor(X_train)

y_train  = df.iloc[:, -1].values # 마지막 값만 
y_train = torch.FloatTensor(y_train)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [133]:
import torch.nn as nn # 모델 생성에 필요한 함수 포함
from torch.optim.adam import Adam

# 모델 학습
# 13 => 100 => ReLU => 50 => ReLU => 1
model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(), # 활성화 함수(비선형)
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model

Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [134]:
for name, param in model.named_parameters():
    print(f"Name: {name}")
    print(f"Shape: {param.shape}")
    print(f"Values: {param}\n")

Name: 0.weight
Shape: torch.Size([100, 13])
Values: Parameter containing:
tensor([[-0.0805,  0.0714,  0.0090,  ..., -0.1843,  0.1688, -0.2331],
        [ 0.0196,  0.0245,  0.0665,  ...,  0.2508,  0.1881, -0.0655],
        [-0.1478,  0.1086,  0.1481,  ...,  0.1826,  0.1640, -0.1714],
        ...,
        [-0.1706,  0.2769,  0.1478,  ...,  0.1223,  0.2247, -0.2108],
        [ 0.0190, -0.1167,  0.1926,  ...,  0.0661,  0.1722,  0.0315],
        [ 0.0911,  0.2089,  0.1088,  ..., -0.1541,  0.1831,  0.1338]],
       requires_grad=True)

Name: 0.bias
Shape: torch.Size([100])
Values: Parameter containing:
tensor([-0.1589, -0.0800,  0.0492,  0.0925, -0.1918, -0.2740,  0.1307, -0.1000,
        -0.2202, -0.2457,  0.1739, -0.1071, -0.2271,  0.1189, -0.1098,  0.0338,
        -0.0639,  0.1841, -0.1588, -0.2070, -0.2122,  0.0736, -0.2313, -0.1823,
         0.2396,  0.2396, -0.2178,  0.2696,  0.0789, -0.1825,  0.1207,  0.0231,
         0.0430, -0.1686,  0.1504, -0.0743, -0.1859,  0.0250,  0.0365, -0.11

In [138]:
optim = Adam(model.parameters(), lr=0.001) # 최적화(탐색 크기 및 속도)함수 선택
criterion = nn.MSELoss() # 손실함수 선택
epochs = 200 

for epoch in range(epochs):
    
    optim.zero_grad() # 기울기 값을 0으로 초기화(누적 방지)
    
    y_pred = model(X_train) # 예측
    
    loss = criterion(y_pred, y_train.view(-1, 1)) # loss 값 계산
    
    loss.backward() # 역전파
    
    optim.step() # 가중치 업데이트(다음 진행)
    
    print('loss : ', loss.item()) # loss 값 확인(계속 감소하면 epoch 증가 고려)

loss :  86.6841812133789
loss :  77.77656555175781
loss :  71.03170776367188
loss :  68.79390716552734
loss :  67.28589630126953
loss :  67.9419174194336
loss :  68.44976043701172
loss :  68.2663803100586
loss :  68.07633972167969
loss :  66.90066528320312
loss :  65.7442398071289
loss :  64.81673431396484
loss :  63.66332244873047
loss :  62.95154571533203
loss :  62.73629379272461
loss :  62.57203674316406
loss :  62.57960510253906
loss :  62.69703674316406
loss :  62.55058670043945
loss :  62.32500076293945
loss :  62.040401458740234
loss :  61.53632354736328
loss :  61.0667610168457
loss :  60.667259216308594
loss :  60.253440856933594
loss :  60.00657272338867
loss :  59.85639572143555
loss :  59.70282745361328
loss :  59.63091278076172
loss :  59.527000427246094
loss :  59.36253356933594
loss :  59.21091079711914
loss :  58.98773956298828
loss :  58.75733184814453
loss :  58.558250427246094
loss :  58.34531784057617
loss :  58.19394302368164
loss :  58.0656852722168
loss :  57.94

In [136]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.1006,  0.0876,  0.0139,  ..., -0.1730,  0.1771, -0.2250],
                      [ 0.0084,  0.0392,  0.0677,  ...,  0.2574,  0.1922, -0.0617],
                      [-0.1491,  0.1210,  0.1543,  ...,  0.1914,  0.1705, -0.1639],
                      ...,
                      [-0.1831,  0.2893,  0.1500,  ...,  0.1290,  0.2292, -0.2064],
                      [-0.0207, -0.0945,  0.2033,  ...,  0.0848,  0.1846,  0.0475],
                      [ 0.0924,  0.2207,  0.1152,  ..., -0.1455,  0.1909,  0.1412]])),
             ('0.bias',
              tensor([-0.1442, -0.0709,  0.0597,  0.0925, -0.2023, -0.2706,  0.1244, -0.1004,
                      -0.2067, -0.2560,  0.1649, -0.1019, -0.2089,  0.1189, -0.0834,  0.0254,
                      -0.0745,  0.1803, -0.1687, -0.1973, -0.2122,  0.0911, -0.2279, -0.1823,
                       0.2351,  0.2284, -0.1590,  0.2718,  0.0551, -0.1096,  0.1248,  0.0330,
                       0.0353, -0.1686, 

In [142]:
# GPU 사용 설정
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

X_train = X_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

optim = Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()
epochs = 200
batch_size = 100

for epoch in range(epochs):
    for temp in range(len(X_train) // batch_size):
        
        s = temp * batch_size # 0 * 100
        e = s + batch_size    # 100
        
        X = X_train[s:e]
        y = y_train[s:e]
    
        optim.zero_grad()
        y_pred = model(X)
        loss = criterion(y_pred, y)
        loss.backward()
        optim.step()

        print('loss : ', loss.item())

loss :  43.22514724731445
loss :  124.25946807861328
loss :  133.8849334716797
loss :  96.34406280517578
loss :  96.43588256835938
loss :  61.28706741333008
loss :  94.13752746582031
loss :  104.20698547363281
loss :  98.22016906738281
loss :  41.66969299316406
loss :  39.087249755859375
loss :  96.01577758789062
loss :  113.0343246459961
loss :  97.66802978515625
loss :  39.473846435546875
loss :  49.48249435424805
loss :  94.46086883544922
loss :  93.47787475585938
loss :  99.20034790039062
loss :  42.14739990234375
loss :  45.523319244384766
loss :  92.48186492919922
loss :  112.20755004882812
loss :  95.83422088623047
loss :  32.702144622802734
loss :  39.57686233520508
loss :  93.03163146972656
loss :  110.5262222290039
loss :  93.8543930053711
loss :  41.547908782958984
loss :  44.547149658203125
loss :  91.92891693115234
loss :  103.3098373413086
loss :  94.24685668945312
loss :  38.37900161743164
loss :  42.073997497558594
loss :  92.34278869628906
loss :  111.3625717163086
los